/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Erroratten (https://sketchfab.com/erroratten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dance-japanese-samurai-ninja-hat-8560f555469a46e085952a890ce9785b
Title: Dance | Japanese Samurai Ninja Hat
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from "../assets/3D/dancer.glb";

const Dancer = ({currentAnimation, ...props}) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions[currentAnimation].reset();
    actions[currentAnimation].play();

  }, [actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.148}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Armature_35"
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials["Material.001"]}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Cube_34" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default Dancer;
